menu:
  Home: /dark-tech/
  Archives: /dark-tech/archives
  About: /about
  GuestBook: /guestbook
  ## You can modify the url to your own personal setting.

widgets:
- search
## the search box
- category
## category
- recent_posts
## your recent posts show
- tagcloud
## the tag of your articles with an effect of wordcloud
- weibo
## your weibo show

- blogroll
## friendly link

blogroll:
  Google: https://www.google.com/
  Github: https://github.com/
  hijiangtao: http://hijiangtao.github.io/

excerpt_link: Continue Reading

comment:
  # disqus: 
  # disqus_shortname: 
## to enable disqus, you need to fill in the disqus_shortname in config.yml

## share plugins at the bottom of the article
share:
  enable: true
  jiathis: true
  twitter: false
  google: false

bottom_link:
  google_plus: 
  ## e.g. 104684175089936429154 for https://plus.google.com/u/0/104684175089936429154/posts
  github: hijiangtao
  twitter: 
  ## e.g. ffff for https://twitter.com/ffff
  weibo: hijiangtao
  facebook: 
  ## e.g. ffff for https://www.facebook.com/ffff
  renren: 
  ## e.g. 333333333 for http://www.renren.com/333333333

logo:
  enable: true  
  ## display img
  src: img/favicon.png 
  ## 32 * 32px, logo img
  apple_icon: img/apple-icon.ico 
  ## logo img for apple icon, 114 * 114 px

## your personal page, could be your github account page, twitter or google plus personal page
## By default its your homepage
personal_site: /

addthis:
  enable: true
  pubid: 
  facebook: true
  twitter: true
  google: true

fancybox: false

## you can change the custom font in head.ejs
CustomFont: true

## google analytics id, e.g.UA-28532742-2
google_analytics: UA-48887175-1

## url of your rss
## it is highly recommanded to use rss plugins, https://github.com/hexojs/hexo-generator-feed
rss: /dark-tech/atom.xml

## for Chinese users
ChineseUser: true
## 默认false. 如果你的访客大部分来自中国, 那么请设置为true, cdn将会调换为百度公共库(360 公共库已停止服务,故部分服务仍将采用Google源), 同时lang和content-language也会被修改
